In [2]:
import numpy as np
import pandas as pd

In [4]:
x=[1,2,3,4,5,6,7,8,9,10]
nx=np.array(x)

In [5]:
print(nx)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
print(nx.shape)

(10,)


In [7]:
ny=np.array([[1,2,3,],[4,5,6]])

In [9]:
print(ny.shape)

(2, 3)


In [10]:
ny

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
one=np.arange(1,100,.2)
one

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4,
       18.6, 18.8, 19. , 19.2, 19.4, 19.6, 19.8, 20. , 20.2, 20.4, 20.6,
       20.8, 21. , 21.2, 21.4, 21.6, 21.8, 22. , 22.2, 22.4, 22.6, 22.8,
       23. , 23.2, 23.4, 23.6, 23.8, 24. , 24.2, 24.4, 24.6, 24.8, 25. ,
       25.2, 25.4, 25.6, 25.8, 26. , 26.2, 26.4, 26.6, 26.8, 27. , 27.2,
       27.4, 27.6, 27.8, 28. , 28.2, 28.4, 28.6, 28.8, 29. , 29.2, 29.4,
       29.6, 29.8, 30. , 30.2, 30.4, 30.6, 30.8, 31

In [13]:
print(one.size)

495


In [14]:
two=np.linspace(1,100,200)
two

array([  1.        ,   1.49748744,   1.99497487,   2.49246231,
         2.98994975,   3.48743719,   3.98492462,   4.48241206,
         4.9798995 ,   5.47738693,   5.97487437,   6.47236181,
         6.96984925,   7.46733668,   7.96482412,   8.46231156,
         8.95979899,   9.45728643,   9.95477387,  10.45226131,
        10.94974874,  11.44723618,  11.94472362,  12.44221106,
        12.93969849,  13.43718593,  13.93467337,  14.4321608 ,
        14.92964824,  15.42713568,  15.92462312,  16.42211055,
        16.91959799,  17.41708543,  17.91457286,  18.4120603 ,
        18.90954774,  19.40703518,  19.90452261,  20.40201005,
        20.89949749,  21.39698492,  21.89447236,  22.3919598 ,
        22.88944724,  23.38693467,  23.88442211,  24.38190955,
        24.87939698,  25.37688442,  25.87437186,  26.3718593 ,
        26.86934673,  27.36683417,  27.86432161,  28.36180905,
        28.85929648,  29.35678392,  29.85427136,  30.35175879,
        30.84924623,  31.34673367,  31.84422111,  32.34

In [15]:
print(two.size)

200


In [17]:
n3=np.random.rand(100)

In [19]:
n3

array([0.97196826, 0.80074803, 0.97308916, 0.71636374, 0.82677472,
       0.21458044, 0.29478843, 0.11674245, 0.57275709, 0.23928025,
       0.80021259, 0.21787955, 0.74087571, 0.74601252, 0.85555996,
       0.86419413, 0.01670928, 0.37288531, 0.98246306, 0.22065861,
       0.00210532, 0.02837029, 0.56999817, 0.89892022, 0.23721551,
       0.44933094, 0.6184467 , 0.49255165, 0.49650539, 0.56748038,
       0.2168298 , 0.97064949, 0.16318597, 0.76631852, 0.64470088,
       0.92167197, 0.94346611, 0.26450314, 0.45415598, 0.80298099,
       0.75168177, 0.60755613, 0.07471866, 0.75427945, 0.16909002,
       0.34506473, 0.11789477, 0.76082947, 0.57658305, 0.92184095,
       0.45015075, 0.40147735, 0.91780923, 0.17546018, 0.12796603,
       0.60683989, 0.32335886, 0.58148749, 0.15476149, 0.20789933,
       0.56236719, 0.12899179, 0.63409959, 0.97819278, 0.44267826,
       0.19124239, 0.16177531, 0.06400841, 0.71861349, 0.98067923,
       0.17669191, 0.3921978 , 0.97224511, 0.27112091, 0.42293

In [20]:
print(n3.size)

100


In [22]:
n4=np.random.randint(1,10,100)
n4

array([4, 1, 3, 4, 1, 3, 3, 1, 8, 6, 4, 6, 2, 3, 4, 7, 4, 2, 6, 3, 3, 5,
       3, 5, 4, 3, 7, 7, 1, 4, 3, 4, 7, 1, 7, 5, 3, 9, 8, 4, 2, 2, 6, 1,
       3, 9, 8, 1, 7, 5, 2, 4, 3, 9, 5, 5, 4, 7, 3, 4, 7, 7, 4, 5, 1, 5,
       2, 8, 4, 1, 5, 8, 4, 6, 1, 5, 3, 9, 8, 4, 6, 5, 9, 8, 9, 8, 5, 7,
       4, 4, 8, 9, 1, 9, 8, 5, 6, 9, 2, 2])

In [23]:
n4.reshape((10,10))

array([[4, 1, 3, 4, 1, 3, 3, 1, 8, 6],
       [4, 6, 2, 3, 4, 7, 4, 2, 6, 3],
       [3, 5, 3, 5, 4, 3, 7, 7, 1, 4],
       [3, 4, 7, 1, 7, 5, 3, 9, 8, 4],
       [2, 2, 6, 1, 3, 9, 8, 1, 7, 5],
       [2, 4, 3, 9, 5, 5, 4, 7, 3, 4],
       [7, 7, 4, 5, 1, 5, 2, 8, 4, 1],
       [5, 8, 4, 6, 1, 5, 3, 9, 8, 4],
       [6, 5, 9, 8, 9, 8, 5, 7, 4, 4],
       [8, 9, 1, 9, 8, 5, 6, 9, 2, 2]])

In [26]:
n4.reshape((5,5,2,2))

array([[[[4, 1],
         [3, 4]],

        [[1, 3],
         [3, 1]],

        [[8, 6],
         [4, 6]],

        [[2, 3],
         [4, 7]],

        [[4, 2],
         [6, 3]]],


       [[[3, 5],
         [3, 5]],

        [[4, 3],
         [7, 7]],

        [[1, 4],
         [3, 4]],

        [[7, 1],
         [7, 5]],

        [[3, 9],
         [8, 4]]],


       [[[2, 2],
         [6, 1]],

        [[3, 9],
         [8, 1]],

        [[7, 5],
         [2, 4]],

        [[3, 9],
         [5, 5]],

        [[4, 7],
         [3, 4]]],


       [[[7, 7],
         [4, 5]],

        [[1, 5],
         [2, 8]],

        [[4, 1],
         [5, 8]],

        [[4, 6],
         [1, 5]],

        [[3, 9],
         [8, 4]]],


       [[[6, 5],
         [9, 8]],

        [[9, 8],
         [5, 7]],

        [[4, 4],
         [8, 9]],

        [[1, 9],
         [8, 5]],

        [[6, 9],
         [2, 2]]]])

In [27]:
n4.reshape((25,4))

array([[4, 1, 3, 4],
       [1, 3, 3, 1],
       [8, 6, 4, 6],
       [2, 3, 4, 7],
       [4, 2, 6, 3],
       [3, 5, 3, 5],
       [4, 3, 7, 7],
       [1, 4, 3, 4],
       [7, 1, 7, 5],
       [3, 9, 8, 4],
       [2, 2, 6, 1],
       [3, 9, 8, 1],
       [7, 5, 2, 4],
       [3, 9, 5, 5],
       [4, 7, 3, 4],
       [7, 7, 4, 5],
       [1, 5, 2, 8],
       [4, 1, 5, 8],
       [4, 6, 1, 5],
       [3, 9, 8, 4],
       [6, 5, 9, 8],
       [9, 8, 5, 7],
       [4, 4, 8, 9],
       [1, 9, 8, 5],
       [6, 9, 2, 2]])

In [28]:
n1= np.random.randint(1,10,(5,5))
n2= np.random.randint(1,10,(5,5))

In [29]:
n1+n2

array([[11, 14,  8, 11, 10],
       [ 9, 12,  5, 14,  5],
       [ 9, 16,  8, 16, 14],
       [10,  8,  4, 15,  7],
       [10, 10, 12, 17, 10]])

In [30]:
n1-n2

array([[ 5,  2,  6, -3, -4],
       [-1, -2,  3, -2,  1],
       [ 7,  0, -4,  2,  0],
       [ 8,  0, -2, -1, -1],
       [ 6, -6,  6,  1, -8]])

In [31]:
n1*n2

array([[24, 48,  7, 28, 21],
       [20, 35,  4, 48,  6],
       [ 8, 64, 12, 63, 49],
       [ 9, 16,  3, 56, 12],
       [16, 16, 27, 72,  9]])

In [32]:
n1/n2

array([[2.66666667, 1.33333333, 7.        , 0.57142857, 0.42857143],
       [0.8       , 0.71428571, 4.        , 0.75      , 1.5       ],
       [8.        , 1.        , 0.33333333, 1.28571429, 1.        ],
       [9.        , 1.        , 0.33333333, 0.875     , 0.75      ],
       [4.        , 0.25      , 3.        , 1.125     , 0.11111111]])

In [33]:
n2**n2

array([[       27,     46656,         1,    823543,    823543],
       [     3125,    823543,         1,  16777216,         4],
       [        1,  16777216,     46656,    823543,    823543],
       [        1,       256,        27,  16777216,       256],
       [        4,  16777216,        27,  16777216, 387420489]])

In [34]:
n1+10

array([[18, 18, 17, 14, 13],
       [14, 15, 14, 16, 13],
       [18, 18, 12, 19, 17],
       [19, 14, 11, 17, 13],
       [18, 12, 19, 19, 11]])

In [35]:
n1.dot(n2)

array([[ 81, 200,  79, 225, 164],
       [ 53, 139,  60, 168, 117],
       [ 89, 212,  76, 262, 185],
       [ 61, 142,  49, 182, 133],
       [ 54, 178,  94, 215, 168]])

In [37]:
n1*n2

array([[24, 48,  7, 28, 21],
       [20, 35,  4, 48,  6],
       [ 8, 64, 12, 63, 49],
       [ 9, 16,  3, 56, 12],
       [16, 16, 27, 72,  9]])

In [38]:
n1,n2

(array([[8, 8, 7, 4, 3],
        [4, 5, 4, 6, 3],
        [8, 8, 2, 9, 7],
        [9, 4, 1, 7, 3],
        [8, 2, 9, 9, 1]]),
 array([[3, 6, 1, 7, 7],
        [5, 7, 1, 8, 2],
        [1, 8, 6, 7, 7],
        [1, 4, 3, 8, 4],
        [2, 8, 3, 8, 9]]))

In [39]:
n6=np.random.randint(1,10,10)
n6

array([9, 8, 9, 8, 6, 3, 7, 1, 7, 4])

In [40]:
n6[0]

9

In [41]:
n6[-1]

4

In [44]:
n6[:4]

array([9, 8, 9, 8])

In [48]:
n7=np.random.randint(1,3,(3,4))
n7

array([[1, 2, 2, 2],
       [2, 1, 1, 1],
       [1, 1, 2, 1]])

In [49]:
print(x[:1])

[1]


In [50]:
print(x[0])

1


In [52]:
print(x[-1])

10


In [53]:
print(x[:,0])

TypeError: list indices must be integers or slices, not tuple

In [54]:
print(x[:2,2:])

TypeError: list indices must be integers or slices, not tuple